# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-09 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='option1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='polls',
            name='option2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
