# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-09 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0002_auto_20160409_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='image',
            field=models.ImageField(default=None, upload_to='my_image/'),
            preserve_default=False,
        ),
    ]
