# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photodate',
            name='uploaded_date',
            field=models.DateField(unique=True),
        ),
    ]
